# Generated by Django 4.0.4 on 2022-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(check=models.Q(('name__length__gte', 5)), name="Card's_name_min_length"),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(check=models.Q(('name__length__gte', 10)), name="Ad's_name_min_length"),
        ),
        migrations.AddConstraint(
            model_name='ad',
            constraint=models.CheckConstraint(check=models.Q(('description__length__gte', 30)), name="Ad's_description_min_length"),
        ),
    ]
