# Generated by Django 4.0.4 on 2022-05-16 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ad_users_card_users_city_ad_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='cities',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='users',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cards', models.ManyToManyField(related_name='parameters', to='catalog.card')),
                ('filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.filter')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='filter',
            name='cards',
            field=models.ManyToManyField(related_name='cards', to='catalog.card'),
        ),
        migrations.AddField(
            model_name='filter',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='catalog.card'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tag', models.BooleanField()),
                ('ads', models.ManyToManyField(related_name='ads', to='catalog.ad')),
                ('cards', models.ManyToManyField(related_name='cards_list', to='catalog.card')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.region'),
        ),
    ]
